# Generated by Django 3.2.7 on 2021-09-15 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('resolved', 'resolved'), ('not resolved', 'not resolved')], default='2', max_length=50)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.employeemodel')),
            ],
        ),
    ]
