# Generated by Django 3.2.5 on 2021-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20210915_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='status',
            field=models.CharField(choices=[('not resolved', 'not resolved'), ('resolved', 'resolved')], default='1', max_length=50),
        ),
        migrations.DeleteModel(
            name='AdminModel',
        ),
    ]
